# Project Name
TARGET = arm_convolution

# Sources
C_SOURCES = arm_convolution_example_f32.c

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
