# Project Name
TARGET = hello

# Sources
CPP_SOURCES = convolution1.cpp -l arm_cortexM7lfsp_math.lib

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
